### ISSUE TITLE
3 of the 4 Fits for Vista are not loading

### ISSUE THREAD

**Issue by rhilliard1976** [Tachyus/.github#5]
## Priority + Rationale
This a P1 bug, 3 of the 4 fits for Vista are not loading in production.

## Describe the bug
It appears that all of the fits for Vista except for 10CBPBFF201953819 are failing to load. The are needing to run a new scenario for Vista this morning, we have a work around, they will use staging. The same fits are loading in staging.

## Steps to Reproduce
1. Go to vista.tachyus.com
2. Go to Fit Config
3. Open any fit except for 10CBPBFF201953819, which loads as expected
4. The screen will be blank because the fit can not be loaded.

## What do you believe the expected behavior is
Is it possible that this is related to the reload?

## Platform details
Vista Production

**Comment by rhilliard1976** [comment]
**Fit Name:** 12ELBT1Completion2018113116
**Well Group:** el1m201810312021
**Flood Engine Call:** getCase

@panesofglass if you need me to run this locally and get the exception, let me know

**Comment by panesofglass** [comment]
Issue moved to [Tachyus/flood-engine #288](https://github.com/Tachyus/flood-engine/issues/288) via [**ZenHub**](https://www.zenhub.com/)
